name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build and publish the image
              run: |
                docker login --username gitgitro --password ${{ secrets.GH_PAT}} ghcr.io
                docker build \
                    --build-arg NEXT_PUBLIC_UMAMI="${{ secrets.NEXT_PUBLIC_UMAMI }}" \
                    -t ghcr.io/gitgitro/my-website:latest .
                docker push ghcr.io/gitgitro/my-website:latest